input: # files to use
    files: [~/cernbox/Analyses/pp5TeV/Ds_wML_mult/inputs/data/ml/Data_Dspp5TeVNoOutlier_pT_1_50.parquet.gzip,
            ~/cernbox/Analyses/pp5TeV/Ds_wML_mult/inputs/MC/MC_comp/Prompt_LHC20a8_pT_1_50.parquet.gzip,
            ~/cernbox/Analyses/pp5TeV/Ds_wML_mult/inputs/MC/MC_comp/FD_LHC20a8_pT_1_50.parquet.gzip
            ]
    treename: null

queries: ['d_len <= 0.5 and (inv_mass < 1.832 or inv_mass > 2.012)',
          'd_len <= 0.5',
          'd_len <= 0.5'] #list of additional queries


output:
    leg_labels: ['Background', 'Prompt D$_s^+$', 'Non-prompt D$_s^+$'] # legend labels
    colors: ['black', 'red', 'blue']
    dir: '/home/fcatalan/cernbox/Analyses/' # output dir

pt_ranges: # ranges in pt to split the data for the comparison
    min: [3] # list
    max: [4] # list

plotting_columns: ['d_len'] 
                   # list of variables to plot

plot_lim_min: [[0.]
               ]
plot_lim_max: [[0.5]
               ]

xaxes_label: ['Decay length (cm)']