Cent010:
    Particle: 'Ds'
    FixSigma: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    SigmaFile: '/home/fcatalan/Desktop/Analyses/PbPb2018/Ds_wML/final/raa/pass3/output/010/ML/raw_yields/RawYields_Ds_MC_010_NewCuts.root'
    SigmaMultFactor: 1.
    FixMean: 0
    MeanFile: ''
    PtMin: [2, 3, 4, 5, 6, 8, 12, 16, 24, 36]    
    PtMax: [3, 4, 5, 6, 8, 12, 16, 24, 36, 50]    
    MassMin: [1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78]    
    MassMax: [2.10, 2.10, 2.06, 2.10, 2.10, 2.10, 2.10, 2.10, 2.10, 2.10]
    Rebin: [3, 3, 3, 4, 4, 4, 4, 5, 5, 6]
    InclSecPeak: [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
    SigmaSecPeak: [0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008]
    SigmaFileSecPeak: '/home/fcatalan/Desktop/Analyses/PbPb2018/Ds_wML/final/raa/pass3/output/010/ML/raw_yields/RawYields_Ds_MC_010_NewCuts.root'
    SigmaMultFactorSecPeak: 1.
    FixSigmaToFirstPeak: 1
    UseLikelihood: 1
    BkgFunc: ['kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo']
    SgnFunc: ['kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus']

Cent3050:
    Particle: 'Ds'
    FixSigma: 0
    SigmaFile: '../ML_DsAnalysis/QM_prel/outputs/3050/raw_yields/RawYieldsDs_3050_pt2_36.root'
    SigmaMultFactor: 1.
    FixMean: 0
    MeanFile: ''
    PtMin: [2, 3, 4, 5, 6, 8, 12, 16, 24]
    PtMax: [3, 4, 5, 6, 8, 12, 16, 24, 36]    
    MassMin: [1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78]    
    MassMax: [2.10, 2.10, 2.10, 2.10, 2.10, 2.10, 2.10, 2.10, 2.10]
    Rebin: [3, 3, 4, 4, 4, 4, 4, 5, 6]
    InclSecPeak: [1, 1, 1, 1, 1, 1, 1, 1, 1]
    SigmaSecPeak: [0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008]
    SigmaFileSecPeak: '/home/fcatalan/Desktop/Analyses/PbPb2018/Ds_wML/final/raa/pass3/output/3050/ML/raw_yields/RawYields_Ds_MC_3050.root'
    SigmaMultFactorSecPeak: 1.
    FixSigmaToFirstPeak: 1
    UseLikelihood: 1
    BkgFunc: ['kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo']
    SgnFunc: ['kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus']
