pp13TeVPrompt:
    Particle: "Lc"
    FixSigma: 0
    SigmaFile: ""
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: "rawYields/ry_mc_basic_PromptEn.root"
    SigmaMultFactor: 1. #float or MinusUnc, PlusUnc
    FixMean: 0
    BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
    MeanFile: ""
    PtMin: [2, 4, 6, 8]
    PtMax: [4, 6, 8, 12]
    MassMin: [2.11, 2.11, 2.11, 2.11]
    MassMax: [2.44, 2.44, 2.44, 2.44]
    Rebin: [5, 5, 5, 5]
    InclSecPeak: [0, 0, 0, 0] # Ds only
    SigmaSecPeak: [0, 0, 0, 0] # Ds only
    SigmaFileSecPeak: 0 # Ds only
    SigmaMultFactorSecPeak: 0 # Ds only
    FixSigmaToFirstPeak: 0
    UseLikelihood: 0
    BkgFunc: ["kPol2", "kPol2", "kPol2", "kPol2"]
    SgnFunc: ["kGaus", "kGaus", "kGaus", "kGaus"]

pp13TeVFD:
    Particle: "Lc"
    FixSigma: 1
    SigmaFile: "rawYields/basic/ry_basic_PromptEn.root"
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: "rawYields/ry_mc_basic_PromptEn.root"
    SigmaMultFactor: 1. #float or MinusUnc, PlusUnc
    FixMean: 0
    BoundMean: 1 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
    MeanFile: "rawYields/basic/ry_basic_PromptEn.root"
    PtMin: [2, 4, 6, 8]
    PtMax: [4, 6, 8, 12]
    MassMin: [2.11, 2.11, 2.11, 2.11]
    MassMax: [2.44, 2.44, 2.44, 2.44]
    Rebin: [5, 5, 5, 5]
    InclSecPeak: [0, 0, 0, 0] # Ds only
    SigmaSecPeak: [0, 0, 0, 0] # Ds only
    SigmaFileSecPeak: 0 # Ds only
    SigmaMultFactorSecPeak: 0 # Ds only
    FixSigmaToFirstPeak: 0
    UseLikelihood: 0
    BkgFunc: ["kPol2", "kPol2", "kPol2", "kPol2"]
    SgnFunc: ["kGaus", "kGaus", "kGaus", "kGaus"]
