pp5TeVPrompt:
    Particle: 'Ds'
    FixSigma: 0
    SigmaFile: ''
    SigmaMultFactor: 1.
    FixMean: 0
    MeanFile: ''
    PtMin: [1, 2, 3, 4, 5, 6, 8, 12, 16]
    PtMax: [2, 3, 4, 5, 6, 8, 12, 16, 24]  
    MassMin: [1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78, 1.78]    
    MassMax: [2.10, 2.10, 2.10, 2.10, 2.10, 2.10, 2.10, 2.10, 2.10]
    Rebin: [6, 6, 6, 6, 6, 8, 8, 10, 14]
    InclSecPeak: [1, 1, 1, 1, 1, 1, 1, 1, 1]
    SigmaSecPeak: [0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008]
    SigmaFileSecPeak: ''
    SigmaMultFactorSecPeak: 1.
    FixSigmaToFirstPeak: 0
    UseLikelihood: 1
    BkgFunc: ['kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo']
    SgnFunc: ['kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus']
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: ""
    BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]

pp5TeVFD:
    Particle: 'Ds'
    FixSigma: 1
    SigmaFile: '../../Analyses/pp5TeV/Ds_wML_mult/outputs/100320/raw_yield/RawYield_Ds_data_norm_pt2_12.root'
    SigmaMultFactor: 1. #float or MinusUnc, PlusUnc
    FixMean: 0
    MeanFile: ''
    PtMin: [2, 4, 6, 8]    
    PtMax: [4, 6, 8, 12]    
    MassMin: [1.78, 1.78, 1.78, 1.78]    
    MassMax: [2.10, 2.10, 2.10, 2.10]
    Rebin: [6, 6, 8, 8]
    InclSecPeak: [1, 1, 1, 1]
    SigmaSecPeak: [0.008, 0.008, 0.008, 0.008]
    SigmaFileSecPeak: ''
    SigmaMultFactorSecPeak: 1.
    FixSigmaToFirstPeak: 0
    UseLikelihood: 1
    BkgFunc: ['kExpo', 'kExpo', 'kExpo', 'kExpo']
    SgnFunc: ['kGaus', 'kGaus', 'kGaus', 'kGaus']
    FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
    SigmaRatioFile: ""
    BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
