runtype: grid #local, test, grid
pathtolocalAOD: '.'
meson: Dplus
system: pp
datadir: /alice/sim/2018/LHC18a4a2_fast/
datapattern: AOD
gridworkdir: NonPromptDplusMC_fast
splitmaxinputfilenum: 20
AliPhysicVersion: vAN-20191130_ROOT6-1
runs: [282343, 282342, 282341, 282340, 282314, 282313, 282312, 282309, 282307, 282306, 282305, 
       282304, 282303, 282302, 282247, 282230, 282229, 282227, 282224, 282206, 282189, 282147, 
       282146, 282127, 282126, 282125, 282123, 282122, 282120, 282119, 282118, 282099, 282098, 
       282078, 282051, 282050, 282031, 282030, 282025, 282021, 282016, 282008, 282367, 282366, 282365]

improver:
    current:
        enable: 1
        period: LHC17pq_G3MC_fast
    upgrade:
        enable: 0
        currentresolfile: ''
        upgraderesolfile: ''
    
task:
    wagonname: Loose_kMB
    cuts:
        infile: /Users/fabrizio/cernbox/ALICE_WORK/AnalysisPbPb2018/DmesonStdAnalysisPbPb/cutobjects/pp/DplustoKpipiCuts_pp_nonprompt_loose_kINT7.root
        objname: AnalysisCuts
    storesparse: 1
    treeML:
        storetree: 1
        fillonlysignal: 1
        enabletrackvars: 0
        PIDoption: kNsigmaDetAndCombPID
    applyML:
        doapplyML: 0
        configfile: ''
        nbins: 300
        min: 0.85
        max: 1.
