infiles:
    signal:
        prompt:
            filename: [~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/ML/pt1_2/Prompt_pT_1_2_ModelApplied.parquet.gzip]
            dirname: null
            treename: null
        feeddown:
            filename: [~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/ML/pt1_2/FD_pT_1_2_ModelApplied.parquet.gzip]
            dirname: null
            treename: null
    secpeak: # only for Ds
        prompt:
            filename: null
            dirname: null
            treename: null
        feeddown:
            filename: null
            dirname: null
            treename: null
    background:
        filename: [~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/ML/pt1_2/Data_pT_1_2_ModelApplied.parquet.gzip]
        dirname: null
        treename: null
        nEvents: 950000000 # number of events for bkg in dataframe
        fractiontokeep: 0.2
        isMC: false # if false bkg from SB
        fitFunc: expo # fit function for bkg from SB, e.g. pol1, pol2, expo
        nSigma: 4 # number of sigma from signal region, used to select SB
        corrfactor:
            filename: null # set null if no MC bkg correction is needed
            histoname: null

    preseleff: 
        filename: ~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/efficiency/Eff_Dplus_pp5TeV_presel_finebins.root
        prompthistoname: hEffPrompt
        feeddownhistoname: hEffFD
    acceptance: ~/cernbox/ALICE_WORK/DmesonAnalysis/accfiles/Acceptance_Toy_DplusKpipi_yfidPtDep_etaDau09_ptDau100_FONLL5ptshape.root

ppRefFile: null

predictions:
    crosssec:
        filename: ~/cernbox/ALICE_WORK/DmesonAnalysis/models/D0DplusDstarPredictions_502TeV_y05_noYShift_all_191017_BDShapeCorrected.root
        histonames: 
            prompt: hDpluskpipipred_max
            feeddown: hDpluskpipifromBpred_max_corr
    Raa: 
        prompt: 1. # can either be a fixed value or a text file
        feeddown: 1. # can either be a fixed value or a text file
        model: null

nExpectedEvents: 950000000
sigmaMB: 50.87e+9 #pb
Taa: 1.

expectedSignalFrom: 'prompt' # Choice between: 'prompt' or 'feeddown'

ptmin: [1]
ptmax: [2]

dfparametercuts:
    name: null 
    min: null
    max: null
    enable: False  # enable cuts over df column query over each df and relative scan histos 

cutvars:
    ML_output_Bkg:
        axisnum: null
        min: 0.002
        max: 0.100
        step: 0.002
        upperlowercut: Upper
    ML_output_Prompt:
        axisnum: null
        min: 0.1
        max: 0.5
        step: 0.005
        upperlowercut: Lower
