infiles:
    signal:
        prompt:
            filename:
                [
                    ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt2_4/Prompt_pT_2_4_ModelApplied.parquet.gzip,
                    ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt4_6/Prompt_pT_4_6_ModelApplied.parquet.gzip,
                    ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt6_8/Prompt_pT_6_8_ModelApplied.parquet.gzip,
                    ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt8_12/Prompt_pT_8_12_ModelApplied.parquet.gzip,
                ]
            dirname: null
            treename: null
        feeddown:
            filename:
                [
                    ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt2_4/FD_pT_2_4_ModelApplied.parquet.gzip,
                    ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt4_6/FD_pT_4_6_ModelApplied.parquet.gzip,
                    ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt6_8/FD_pT_6_8_ModelApplied.parquet.gzip,
                    ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt8_12/FD_pT_8_12_ModelApplied.parquet.gzip,
                ]
            dirname: null
            treename: null
    secpeak: # only for Ds
        prompt:
            filename: null
            dirname: null
            treename: null
        feeddown:
            filename: null
            dirname: null
            treename: null
        mean: 0 # fixed values of mean and sigma, used if histogram is not provided
        sigma: 0
    background:
        filename:
            [
                ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt2_4/Data_pT_2_4_ModelApplied.parquet.gzip,
                ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt4_6/Data_pT_4_6_ModelApplied.parquet.gzip,
                ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt6_8/Data_pT_6_8_ModelApplied.parquet.gzip,
                ~/DmesonAnalysis/ML/trained_models/LctopK0s/cospV0/pt8_12/Data_pT_8_12_ModelApplied.parquet.gzip,
            ]
        dirname: null
        treename: null
        nEvents: 1800000000 # number of events for bkg in dataframe
        fractiontokeep: [0.08, 0.1, 0.1, 0.2]
        # fractiontokeep: [0.1, 0.1, 0.2]
        isMC: false # if false bkg from SB
        fitFunc: pol2 # fit function for bkg from SB, e.g. pol1, pol2, expo
        nSigma: 4 # number of sigma from signal region, used to select SB
        corrfactor:
            filename: null # set null if no MC bkg correction is needed
            histoname: null

    preseleff:
        filename: ~/DmesonAnalysis/efficiencies/eff_cospV0_noMLcut.root
        prompthistoname: hEffPrompt
        feeddownhistoname: hEffFD
    acceptance: ~/DmesonAnalysis/accfiles/Acceptance_Toy_LcK0Sp_yfidPtDep_etaDau09_ptDau100_promptD0FONLL13ptshape.root

ppRefFile: null

predictions:
    crosssec:
        filename: ~/DmesonAnalysis/models/fonll/feeddown/DmesonLcPredictions_13TeV_y05_FFptDepLHCb_BRpythia8_PDG2020_PromptLcMod.root
        histonames:
            prompt: hLcK0sppred_max
            feeddown: hLcK0spfromBpred_max_corr
    Raa:
        prompt: 1. # can either be a fixed value or a text file
        feeddown: 1. # can either be a fixed value or a text file
        model: null

nExpectedEvents: 1800000000
sigmaMB: 57.8e+9 #pb
Taa: 1.

expectedSignalFrom: "feeddown" # Choice between: 'prompt' or 'feeddown'

ptmin: [2, 4, 6, 8]
ptmax: [4, 6, 8, 12]

dfparametercuts:
    name: null
    min: null
    max: null
    enable: False # enable cuts over df column query over each df and relative scan histos

cutvars:
    ML_output_Bkg:
        axisnum: null
        min: 0.02
        max: 0.500
        step: 0.01
        upperlowercut: Upper
    ML_output_FD:
        axisnum: null
        min: 0.1
        max: 0.9
        step: 0.01
        upperlowercut: Lower

specifier: cospV0
