infiles:
    signal:
        prompt:
            filename: [/home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt1_2/Prompt_pT_1_2_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt2_4/Prompt_pT_2_4_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt4_8/Prompt_pT_4_8_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt8_12/Prompt_pT_8_12_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt1_2/Prompt_pT_1_2_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt2_4/Prompt_pT_2_4_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt4_8/Prompt_pT_4_8_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt8_12/Prompt_pT_8_12_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt1_2/Prompt_pT_1_2_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt2_4/Prompt_pT_2_4_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt4_8/Prompt_pT_4_8_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt8_12/Prompt_pT_8_12_ModelApplied.parquet.gzip
                       ]
            dirname: null
            treename: null
        feeddown:
            filename: [/home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt1_2/FD_pT_1_2_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt2_4/FD_pT_2_4_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt4_8/FD_pT_4_8_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt8_12/FD_pT_8_12_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt1_2/FD_pT_1_2_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt2_4/FD_pT_2_4_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt4_8/FD_pT_4_8_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt8_12/FD_pT_8_12_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt1_2/FD_pT_1_2_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt2_4/FD_pT_2_4_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt4_8/FD_pT_4_8_ModelApplied.parquet.gzip,
                       /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt8_12/FD_pT_8_12_ModelApplied.parquet.gzip
                       ]
            dirname: null
            treename: null
    secpeak: # only for Ds
        prompt:
            filename: null
            dirname: null
            treename: null
        feeddown:
            filename: null
            dirname: null
            treename: null
        mean: 0 # fixed values of mean and sigma, used if histogram is not provided
        sigma: 0
    background:
        filename: [/home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt1_2/Data_pT_1_2_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt2_4/Data_pT_2_4_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt4_8/Data_pT_4_8_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_1/pt8_12/Data_pT_8_12_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt1_2/Data_pT_1_2_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt2_4/Data_pT_2_4_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt4_8/Data_pT_4_8_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_2/pt8_12/Data_pT_8_12_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt1_2/Data_pT_1_2_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt2_4/Data_pT_2_4_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt4_8/Data_pT_4_8_ModelApplied.parquet.gzip,
                   /home/alidock/DmesonAnalysis/ML/AnalysisDs/MLoutput_ITS2/ML_output_apply_test_set_3/pt8_12/Data_pT_8_12_ModelApplied.parquet.gzip
                   ]
        dirname: null
        treename: null
        nEvents: 635624 # number of events for bkg in dataframe   
        fractiontokeep: 1 
        isMC: True # if false bkg from SB
        fitFunc: expo # fit function for bkg from SB, e.g. pol1, pol2, expo
        nSigma: 4 # number of sigma from signal region, used to select SB
        corrfactor:
            filename: /home/alidock/DmesonAnalysis/optimisation/BkgCorrFactor/BkgCorrFact_ITS1_AllpT.root # set null if no MC bkg correction is needed
            histoname: hBkgCorrFactorOverPt

    preseleff: 
        filename: /home/alidock/DmesonAnalysis/outEff_AllTest.root
        prompthistoname: hEffPrompt
        feeddownhistoname: hEffFD
    acceptance: /home/alidock/DmesonAnalysis/accfiles/Acceptance_Toy_DsKKpi_yfidPtDep_etaDau09_ptDau100_FONLL5ptshape.root

ppRefFile: null

predictions:
    crosssec:
        filename: /home/alidock/DmesonAnalysis/models/D0DplusDstarPredictions_502TeV_y05_all_021016_BDShapeCorrected.root
        histonames: 
            prompt: hDsPhipitoKkpipred_max
            feeddown: hDsPhipitoKkpifromBpred_max_corr
    Raa: 
        prompt: /home/alidock/DmesonAnalysis/models/tamu/Ds_TAMU_RAA_5TeV_010.txt # can either be a fixed value or the path to a text file
        feeddown: /home/alidock/DmesonAnalysis/models/tamu/NonPromptDs_TAMU_RAA_5TeV_010.txt # can either be a fixed value or a text file
        model: tamu # avaliable models: 'phsd', 'Catania', 'tamu', 'MCatsHQ'        

nExpectedEvents: 7700000000
BR: 0.0227
fractoD: 0.092
sigmaMB: 1 #pb
Taa: 0.00000002307 #pb-1

expectedSignalFrom: 'feeddown' # Choice between: 'prompt' or 'feeddown'

ptmin: [1, 2, 4, 6, 8] #GeV
ptmax: [2, 4, 6, 8, 12] #GeV

dfparametercuts:
    name: 'dca' 
    min: [0, 0.005, 0.01 ] # , 0.015 , 0.020 , 0.025 , 0.030 , 0.040 , 0.050 , 0.075 ] #cm
    max: [0.005 , 0.01 , 0.015 ] #, 0.020 , 0.025 , 0.030 , 0.040 , 0.050 , 0.075 , 0.10] #cm
    enable: False  # enable cuts over df column query over each df and relative scan histos 

cutvars:
    ML_output_Bkg:
        axisnum: null
        min: 0.
        max: 2.
        step: 0.2
        upperlowercut: Upper
    ML_output_FD:
        axisnum: null
        min: -2.
        max: 0.
        step: 0.1
        upperlowercut: Lower


