isMC: yes
filename:
    [
        /data/shared/NonPromptLc/MC/LHC20f4c_2016/AnalysisResults_Bayes.root,
        /data/shared/NonPromptLc/MC/LHC20f4b_2017/AnalysisResults_Bayes.root,
        /data/shared/NonPromptLc/MC/LHC20f4a_2018/AnalysisResults_Bayes.root,
    ]

dirname: PWGHF_D2H_NonPromptLctopK0sLoose
listname: coutputNonPromptLctopK0sLoose
sparsenameAll: null
sparsenamePrompt: fnSparseAcc_fromC # ThnSparse with rec candidates
sparsenameFD: fnSparseAcc_fromB # ThnSparse with rec candidates
sparsenameGenPrompt: fnSparseAcc_fromC # ThnSparse with generated candidates
sparsenameGenFD: fnSparseAcc_fromB # ThnSparse with generated candidates
enableSecPeak: no #no second peak for D+
sparsenamePromptSecPeak: null
sparsenameFDSecPeak: null
sparsenameGenPromptSecPeak: null
sparsenameGenFDSecPeak: null
normname: NormalizationCounter
histoevname: hNEvents

#info for trees (files can be different if trees are filtered or with applied ML models)
tree:
    particle: Lc #needed to define binning for invariant-mass histo
    filenameAll: null #not needed for MC
    filenamePrompt:
        [
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/nsigcospV0/pt2_4/Prompt_pT_2_4_ModelApplied.parquet.gzip,
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/nsigcospV0/pt4_6/Prompt_pT_4_6_ModelApplied.parquet.gzip,
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/nsigcospV0/pt6_8/Prompt_pT_6_8_ModelApplied.parquet.gzip,
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/nsigcospV0/pt8_12/Prompt_pT_8_12_ModelApplied.parquet.gzip,
        ]
    filenameFD:
        [
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/nsigcospV0/pt2_4/FD_pT_2_4_ModelApplied.parquet.gzip,
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/nsigcospV0/pt4_6/FD_pT_4_6_ModelApplied.parquet.gzip,
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/nsigcospV0/pt6_8/FD_pT_6_8_ModelApplied.parquet.gzip,
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/nsigcospV0/pt8_12/FD_pT_8_12_ModelApplied.parquet.gzip,
        ]
    dirname: null
    treename: null
