isMC: yes
isReducedVariables: no
isWithPtB: no
filename: /home/fcatalan/Desktop/Analyses/PbPb2018/Ds_wML/final/raa/pass3/input/MC/010/D2H_MLapplied/AnalysisResultsDs_MC_010_ML_LHC20g2a_Tot.root
dirname: PWGHF_D2H_InvMassDs_MLappl010
listname: coutputDs_MLappl010
sparsenameAll: null
sparsenamePrompt: fnSparseReco_fromC
sparsenameFD: fnSparseReco_fromB
sparsenameGenPrompt: fnSparseAcc_fromC
sparsenameGenFD: fnSparseAcc_fromB
enableSecPeak: yes
sparsenamePromptSecPeak: fnSparseRecoDplus_fromC
sparsenameFDSecPeak: fnSparseRecoDplus_fromB
sparsenameGenPromptSecPeak: fnSparseAccDplus_fromC
sparsenameGenFDSecPeak: fnSparseAccDplus_fromB
normname: NormalizationCounter
histoevname: hNEvents
shiftForRedVariables: 11 # dependent on the sparse defined in the AliPhysics task