isMC: no
filename:
    [
        /data/shared/NonPromptLc/data/LHC16_kl/AnalysisResults_allPIDvars.root,
        /data/shared/NonPromptLc/data/LHC16_deghjop/AnalysisResults_allPIDvars.root,
        /data/shared/NonPromptLc/data/LHC17_cefhijklmor/AnalysisResults_allPIDvars.root,
        /data/shared/NonPromptLc/data/LHC18_bdefghijklmnop/AnalysisResults_allPIDvars.root,
    ]
dirname: PWGHF_D2H_NonPromptLctopK0sLoose
listname: coutputNonPromptLctopK0sLoose
sparsenameAll: hMassPtCutVarsAll
enableSecPeak: no #always no for data
normname: NormalizationCounter
histoevname: hNEvents

#info for trees (files can be different if trees are filtered or with applied ML models)
tree:
    particle: "Lc"
    filenameAll:
        [
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/basic/pt2_4/Data_pT_2_4_ModelApplied.parquet.gzip,
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/basic/pt4_6/Data_pT_4_6_ModelApplied.parquet.gzip,
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/basic/pt6_8/Data_pT_6_8_ModelApplied.parquet.gzip,
            /home/dbattistini/DmesonAnalysis/ML/trained_models/LctopK0s/basic/pt8_12/Data_pT_8_12_ModelApplied.parquet.gzip,
        ]
    dirname: PWGHF_D2H_NonPromptLctopK0sLoose
    treename: treeML
