input:
    filename: ~/cernbox/alice_work/trains/pp13TeV/AnalysisResults.root
    suffix: 11
    prefix: HM
    HFsuffix: ''

rawyields:
    filename: ~/cernbox/alice_work/analyses/DpFemtoHM13TeV/outputs/rawyields/RawYieldsDplus_pp13TeV_HMV0M_tight2_finebins.root
    histoname: SandBDiffNsigma/hRawYieldsSoverB_2.00sigma # 2sigma window
    systpurity: [0.02, 0.02, 0.02, 0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01 ] # null if not available

fractions:
    beauty:
        enable: true
        filename: ~/cernbox/alice_work/analyses/DpFemtoHM13TeV/outputs/fractions/datadriven/DataDrivenFraction_Dplus_pp13TeV_HMV0M_femto_tight2.root
        histoname: hFDFrac
        systbeauty: [0.05, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02 ] # null if not available
    Dstar:
        enable: true
        filename: ~/cernbox/alice_work/analyses/DpFemtoHM13TeV/outputs/fractions/dstar/DplusFromDstar_pp5TeV_decayer_Pythia8.root
        histoname: hFrac
        graphname: gFrac

output:
    directory: '~/cernbox/alice_work/analyses/DpFemtoHM13TeV/outputs/fractions/purity'
    suffix: _masswindow_2sigma_sphericity_0_1_tight_2
    addTDirectory: false # to add a TDirectory in output root file named as the suffix