10433: # Ds1+
  D: # D*+, from pp 13 TeV MB https://alice-notes.web.cern.ch/node/1338
    ptmins: [1., 1.5, 2., 2.5, 3., 3.5, 4., 4.5, 5., 5.5, 6., 6.5, 7., 7.5, 8., 9., 10., 12., 16., 24., 36.]
    ptmaxs: [1.5, 2., 2.5, 3., 3.5, 4., 4.5, 5., 5.5, 6., 6.5, 7., 7.5, 8., 9., 10., 12., 16., 24., 36., 50.]
    syst: [0.045, 0.045, 0.05, 0.05, 0.05, 0.05, 0.055, 0.055, 0.055, 0.055, 0.055, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.065, 0.065, 0.065]
  V0: # K0s, ~ from pp 13TeV MB https://alice-notes.web.cern.ch/node/425 and https://alice-publications.web.cern.ch/node/3429
    ptmins: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.6, 1.8, 2., 2.5, 3., 3.5, 4., 5., 6., 8., 10.]
    ptmaxs: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.6, 1.8, 2., 2.5, 3., 3.5, 4., 5., 6., 8., 10., 24.]
    syst: [0., 0.018, 0.016, 0.015, 0.015, 0.014, 0.011, 0.009, 0.006, 0.006, 0.006, 0.008, 0.009, 0.010, 0.013, 0.018, 0.023, 0.026, 0.03, 0.03, 0.02, 0.02, 0.05, 0.095]
    systMat: [0.047, 0.039, 0.033, 0.028, 0.023, 0.02, 0.017, 0.014, 0.012, 0.011, 0.009, 0.008, 0.007, 0.006, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005]

435: # Ds2*+
  D: # D+, from pp 13 TeV MB https://alice-notes.web.cern.ch/node/1339
    ptmins: [0., 1., 1.5, 2., 2.5, 3., 3.5, 4., 4.5, 5., 5.5, 6., 6.5, 7., 7.5, 8., 9., 10., 12., 16., 24., 36.]
    ptmaxs: [1., 1.5, 2., 2.5, 3., 3.5, 4., 4.5, 5., 5.5, 6., 6.5, 7., 7.5, 8., 9., 10., 12., 16., 24., 36., 50.]
    syst: [0.035, 0.035, 0.035, 0.045, 0.045, 0.05, 0.05, 0.06, 0.06, 0.06, 0.06, 0.065, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07]
  V0: # K0s, ~ from pp 13TeV MB https://alice-notes.web.cern.ch/node/425 and https://alice-publications.web.cern.ch/node/3429
    ptmins: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.6, 1.8, 2., 2.5, 3., 3.5, 4., 5., 6., 8., 10.]
    ptmaxs: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.6, 1.8, 2., 2.5, 3., 3.5, 4., 5., 6., 8., 10., 24.]
    syst: [0., 0.018, 0.016, 0.015, 0.015, 0.014, 0.011, 0.009, 0.006, 0.006, 0.006, 0.008, 0.009, 0.010, 0.013, 0.018, 0.023, 0.026, 0.03, 0.03, 0.02, 0.02, 0.05, 0.095]
    systMat: [0.047, 0.039, 0.033, 0.028, 0.023, 0.02, 0.017, 0.014, 0.012, 0.011, 0.009, 0.008, 0.007, 0.006, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005]

413: # D*
  D: # D0, from pp 13 TeV vs. mult https://alice-notes.web.cern.ch/node/993
    ptmins: [1., 2., 4., 6., 8., 12.]
    ptmaxs: [2., 4., 6., 8., 12., 24.]
    syst: [0.035, 0.04, 0.05, 0.05, 0.05, 0.05]
  V0: # soft pion, from pp 13 TeV vs. mult https://alice-notes.web.cern.ch/node/993
    ptmins: [0.]
    ptmaxs: [24.]
    syst: [0.02]
    systMat: [0.]