rawyields:
    inputdir: ../AnalysisNonPromptDpp2017/Dplus/outputs/rawyields
    inputfiles: [ RawYields_Dplus_pp5TeV_FD5.root, RawYields_Dplus_pp5TeV_FD6.root, RawYields_Dplus_pp5TeV_FD7.root, RawYields_Dplus_pp5TeV_FD8.root, RawYields_Dplus_pp5TeV_FD9.root, RawYields_Dplus_pp5TeV_FD10.root, RawYields_Dplus_pp5TeV_FD11.root, RawYields_Dplus_pp5TeV_FD12.root, RawYields_Dplus_pp5TeV_FD13.root, RawYields_Dplus_pp5TeV_FD14.root, RawYields_Dplus_pp5TeV_FD15.root, RawYields_Dplus_pp5TeV_FD16.root, RawYields_Dplus_pp5TeV_FD17.root, RawYields_Dplus_pp5TeV_FD18.root, RawYields_Dplus_pp5TeV_FD19.root, RawYields_Dplus_pp5TeV_FD20.root, RawYields_Dplus_pp5TeV_FD21.root, RawYields_Dplus_pp5TeV_FD22.root, RawYields_Dplus_pp5TeV_FD23.root, RawYields_Dplus_pp5TeV_FD24.root, RawYields_Dplus_pp5TeV_FD25.root ] #, RawYields_Dplus_pp5TeV_FD26.root
    histoname: hRawYields

efficiencies:
    inputdir: ../AnalysisNonPromptDpp2017/Dplus/outputs/efficiency
    inputfiles: [ EffAcc_Dplus_pp5TeV_FD5.root, EffAcc_Dplus_pp5TeV_FD6.root, EffAcc_Dplus_pp5TeV_FD7.root, EffAcc_Dplus_pp5TeV_FD8.root, EffAcc_Dplus_pp5TeV_FD9.root, EffAcc_Dplus_pp5TeV_FD10.root, EffAcc_Dplus_pp5TeV_FD11.root, EffAcc_Dplus_pp5TeV_FD12.root, EffAcc_Dplus_pp5TeV_FD13.root, EffAcc_Dplus_pp5TeV_FD14.root, EffAcc_Dplus_pp5TeV_FD15.root, EffAcc_Dplus_pp5TeV_FD16.root, EffAcc_Dplus_pp5TeV_FD17.root, EffAcc_Dplus_pp5TeV_FD18.root, EffAcc_Dplus_pp5TeV_FD19.root, EffAcc_Dplus_pp5TeV_FD20.root, EffAcc_Dplus_pp5TeV_FD21.root, EffAcc_Dplus_pp5TeV_FD22.root, EffAcc_Dplus_pp5TeV_FD23.root, EffAcc_Dplus_pp5TeV_FD24.root, EffAcc_Dplus_pp5TeV_FD25.root ] #, EffAcc_Dplus_pp5TeV_FD26.root
    histonames:
        prompt: hAccEffPrompt
        feeddown: hAccEffFD

minimisation:
    correlated: true #true --> fully correlated, false --> fully uncorrelated (if false, RawYieldSmearing automatically enabled)
    doRawYieldSmearing: false

theorydriven:
    enableFc: true
    enableNb: true
    predictions:
        crosssec: 
            inputfile: models/D0DplusDstarPredictions_502TeV_y05_noYShift_all_191017_BDShapeCorrected.root
            histonames: 
                prompt: hDpluskpipipred
                feeddown: hDpluskpipifromBpred
        Raa:
            prompt: 1.
            feeddown: 1.
            model: null
    # below only needed for Nb
    sigmaMB: 50.87e+9
