rawyields:
    inputdir: ~/cernbox/Analyses/pp5TeV/Ds_wML_mult/outputs/100320/data_driven_fprompt/raw_yield
    inputfiles: [RawYieldsDs_pp5TeV_FDen_neg_049.root,
                 RawYieldsDs_pp5TeV_FDen_neg_053.root, 
                 RawYieldsDs_pp5TeV_FDen_neg_057.root,
                 RawYieldsDs_pp5TeV_FDen_neg_061.root,
                 RawYieldsDs_pp5TeV_FDen_neg_065.root, 
                 RawYieldsDs_pp5TeV_FDen_neg_069.root,
                 RawYieldsDs_pp5TeV_FDen_neg_073.root,
                 RawYieldsDs_pp5TeV_FDen_neg_077.root,
                 RawYieldsDs_pp5TeV_FDen_neg_081.root, 
                 RawYieldsDs_pp5TeV_FDen_neg_085.root,
                 RawYieldsDs_pp5TeV_FDen_neg_089.root,
                 RawYieldsDs_pp5TeV_FDen_pos_092.root
                ]
    histoname: hRawYields

efficiencies:
    inputdir: ~/cernbox/Analyses/pp5TeV/Ds_wML_mult/outputs/100320/data_driven_fprompt/eff
    inputfiles: [Eff_times_Acc_Ds_pp5TeV_FDen_neg_049.root,
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_053.root, 
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_057.root,
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_061.root,
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_065.root, 
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_069.root,
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_073.root,
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_077.root,
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_081.root, 
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_085.root,
                 Eff_times_Acc_Ds_pp5TeV_FDen_neg_089.root,
                 Eff_times_Acc_Ds_pp5TeV_FDen_pos_092.root
                ]
    histonames:
        prompt: hAccEffPrompt
        feeddown: hAccEffFD

minimisation:
    correlated: true #true --> fully correlated, false --> fully uncorrelated (if false, RawYieldSmearing automatically enabled)
    doRawYieldSmearing: false

theorydriven:
    enableFc: true
    enableNb: true
    predictions:
        crosssec: 
            inputfile: models/D0DplusDstarPredictions_502TeV_y05_noYShift_all_191017_BDShapeCorrected.root
            histonames: 
                prompt: hDsPhipitoKkpipred
                feeddown: hDsPhipitoKkpifromBpred
        Raa:
            prompt: 1.
            feeddown: 1.
            model: null
    # below only needed for Nb
    sigmaMB: 50.87e+9
